"""add_friendship_and_user_avatar

Revision ID: 66b76a2185b0
Revises: ba009343b973
Create Date: 2025-05-17 15:45:31.589561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b76a2185b0'
down_revision: Union[str, None] = 'ba009343b973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.add_column('user', sa.Column('avatar', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about')
    op.drop_column('user', 'avatar')
    op.drop_table('friendships')
    # ### end Alembic commands ###
