"""add_post_reaction

Revision ID: c7a839cfbd8d
Revises: 66b76a2185b0
Create Date: 2025-05-18 12:20:49.011878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'c7a839cfbd8d'
down_revision: Union[str, None] = '66b76a2185b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    reaction_enum = ENUM('LIKE', 'DISLIKE', name='postreactionenum', create_type=False)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reaction', reaction_enum, nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_reaction')
    )
    op.create_index(op.f('ix_post_reactions_uuid'), 'post_reactions', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_reactions_uuid'), table_name='post_reactions')
    op.drop_table('post_reactions')
    # ### end Alembic commands ###
